language: go
go:
- 1.3
before_install:
- go get -d -v ./... && go build -v ./...
script:
- go test -v ./...
- go install -v ./...
notifications:
  slack:
    secure: t/2Qo7vdDGc549/XzNSQXyz3pVWlvwfX3Ofd8hojPhGy/d3OirQRqm3d823nG5UztposwK1BMn/IFd2gVTlS/bw3qLb1N1uAExKQnEnJwn4+X6hbpdpgsn2U5a0W7IQ1MdN8SQ1biJyWp+O9VueB9syQs9atAfMObLTbBcdw4/0=
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "XqEqKA/ex9bE5jWfitdTcKzLaA02hL80AluY2IqZ3sqpdcKW3O8xLw2jYfomtRy0WdfNRedzGHUTWSRKS26nLc5539e1f7/8PO0PBDi1MyPwBoKkixjliDb4H6llVCvweEMiLseSYks+j291oJpsGNmiVJ+681/myHuNr0OrzVM="
  app:
    secure: "NxVAb5ZgpFQB8LisNX4RA3uehJfwb1ruY2Fet9q/2xG9eOvmscNgLYODP5eZjNJboyBnkkhZ4ToiY+JOZ7wizFoZRqFDahdia5pkbx6d+GnerGCAv9btUyH3uDTZr0VM6X0zdcZmUxr5udmGT229i3mx42IiwYxmuBXrCNhqDSU="
    secure: "rvjCaXn7q6/0zZMZTAPJowTwiBII3KUJq8xbwD+7npuAyYIRYF0MSlSrOAgvkcfHNrjr8yMSBbVhLwXVzV9YvodWDMp29GsepeIMa7bF2zFEPQEBYhnj+8YZLJUq3EdHn/9Uig5FoyhCh5wrXwIcShn3DjVCa6IptlJgQoE6Gvw="
  on:
    repo: yuruga/skthub
    branch:
      - master
      - develop
